name: benchmarks
on: [ workflow_call, workflow_dispatch ]
jobs:
  codspeed:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: cache warmup
        uses: ./.github/actions/use-bun-cache
      - name: node modules
        shell: bash
        run: devenv shell bun i
      - name: bench
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: devenv shell bun run bench:regress
  bench:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: cache warmup
        uses: ./.github/actions/use-bun-cache
      - name: node modules
        shell: bash
        run: devenv shell bun i
      - name: bench
        run: devenv shell bun run bench
