name: CD
on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: run verify
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm i
          pnpm verify
  test:
    runs-on: ubuntu-latest
    needs: [ verify ]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: run tests
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm i
          pnpm ci:codecov:test
      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: upload test results
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
  regress:
    runs-on: ubuntu-latest
    needs: [ verify ]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: node modules
        shell: bash
        run: devenv shell pnpm i
      - name: bench
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: devenv shell pnpm ci:codspeed:regress
  publish:
    runs-on: ubuntu-latest
    needs: [verify, regress, test]
    permissions:
      contents: read
      id-token: write
    environment: production
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: publish packages
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm i
          pnpm publish
