name: CD
on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use bun cache
        uses: ./.github/actions/use-bun-cache
      - name: run verify
        shell: devenv shell bash -- -e {0}
        run: |
          bun i
          bun run verify
  tests:
    runs-on: ubuntu-latest
    needs: [ verify ]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use bun cache
        uses: ./.github/actions/use-bun-cache
      - name: run tests
        shell: devenv shell bash -- -e {0}
        run: |
          bun i
          bun run test:coverage
      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: upload test results
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
  regress:
    runs-on: ubuntu-latest
    needs: [ verify ]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use bun cache
        uses: ./.github/actions/use-bun-cache
      - name: node modules
        shell: bash
        run: devenv shell bun i
      - name: bench
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: devenv shell bun run bench:regress
  # TODO: npm publishing stub
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: [ verify, regress, coverage ]
  #   environment: production
