name: '@use-raf/state'
on: [ workflow_call ]
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: run lint
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm i
          pnpm --filter @use-raf/state lint
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: run test
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm i
          pnpm --filter @use-raf/state test
  bench:
    runs-on: ubuntu-latest
    needs: [ test ]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: run bench
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm i
          pnpm --filter @use-raf/state bench
  codspeed:
    runs-on: ubuntu-latest
    needs: [ test ]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: node modules
        shell: bash
        run: devenv shell pnpm i
      - name: bench
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: devenv shell pnpm --filter @use-raf/state bench:regress
