name: tests
on: [ workflow_call ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: cache warmup
        uses: ./.github/actions/use-bun-cache
      - name: node modules
        shell: bash
        run: devenv shell bun i
      - name: run tests
        shell: bash
        run: devenv shell bun run test
