name: '@use-raf/timer'
on: [ workflow_call ]
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: run lint
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm i --frozen-lockfile
          pnpm --filter @use-raf/timer lint
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup environment
        uses: ./.github/actions/setup-devenv
      - name: use pnpm cache
        uses: ./.github/actions/use-pnpm-cache
      - name: run test
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm i --frozen-lockfile
          pnpm --filter @use-raf/timer test
